name: Node CI

on:
  push:
    branches:
    - master
    - main
    - develop
    - feature/*

  pull_request:
    branches:
    - master
    - main
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: npm install, lint, build, test and prepare coverage reports
        run: |
          npm ci
          npm run typecheck --if-present
          npm run lint --if-present
          npm run build --if-present
          npm test
          npm run coverage
          # # /home/runner/work/shopping-cart-ts/shopping-cart-ts/src/cart/cart.ts
          # sed -i "s|SF:/.*/src/|SF:/github/workspace/src/|g" coverage/lcov.info
        env:
          CI: true

      # - name: Coveralls
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.github_token }}

      # - name: Codecov
      #   uses: codecov/codecov-action@v1.0.3
      #   with:
      #     token: ${{secrets.CODECOV_TOKEN}}
      #     file: ./coverage/coverage-final.json
      #     flags: unittests

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
