name: Node CI

on:
  push:
    branches:
    - master
    - develop
    - feature/*

  pull_request:
    branches:
    - master
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        version: 12.x

    - name: npm install, lint, build, and test
      run: |
        npm ci
        npm run lint --if-present
        npm run build --if-present
        npm test
        npm run coverage
      env:
        CI: true

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
